{
  description = "bem-fmm-python";
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    self,
    nixpkgs,
    treefmt-nix,
  }: let
    inherit (nixpkgs) lib;
    eachSystem = f:
      lib.genAttrs ["x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin"] (
        system: f nixpkgs.legacyPackages.${system}
      );
    treefmtEval = eachSystem (
      pkgs:
        treefmt-nix.lib.evalModule pkgs {
          projectRootFile = "flake.nix";
          programs.alejandra.enable = true;
          programs.black.enable = true;
          # settings are in pyproject.toml
          programs.isort.enable = true;
          # generated by pyside6-uic, only black formats them
          settings.formatter.isort.excludes = ["src/bemfmm/gui/ui_*.py"];
        }
    );
  in {
    formatter = eachSystem (pkgs: treefmtEval.${pkgs.stdenv.hostPlatform.system}.config.build.wrapper);
    checks = eachSystem (pkgs: {
      formatting = treefmtEval.${pkgs.stdenv.hostPlatform.system}.config.build.check self;
    });
    devShells = eachSystem (
      pkgs: let
        python = pkgs.python314;
        # loaded at run time by the PyPI wheels in .venv (numpy, vtk, PySide6),
        # which look for them in the usual system places, not in the nix store
        libs = with pkgs; [
          stdenv.cc.cc.lib
          zstd
          zlib
          libGL
          glib
          fontconfig
          freetype
          dbus
          krb5
          libxkbcommon
          wayland
          libx11
          libxext
          libxrender
          libxi
          libxrandr
          libxcursor
          libxfixes
          libsm
          libice
          libxcb
          libxcb-cursor
          libxcb-util
          libxcb-wm
          libxcb-image
          libxcb-keysyms
          libxcb-render-util
        ];
      in {
        default = pkgs.mkShell {
          # a plain python, every package comes from pyproject.toml into .venv
          packages =
            [
              python
              pkgs.uv
              pkgs.ruff
              pkgs.black
              pkgs.isort
              pkgs.basedpyright
              pkgs.alejandra
            ]
            ++ lib.optionals pkgs.stdenv.isLinux [pkgs.gdb];

          shellHook =
            lib.optionalString pkgs.stdenv.isLinux
            /*
            sh
            */
            ''
              # the gpu driver of the system first (NixOS keeps it there), then the rest
              export LD_LIBRARY_PATH="/run/opengl-driver/lib:${lib.makeLibraryPath libs}''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
              # the 3D view renders through GLX, which Qt only offers on xcb
              export QT_QPA_PLATFORM=xcb
            ''
            +
            /*
            sh
            */
            ''
              # PySide6 brings its own Qt, plugins and styles of the desktop Qt
              # (kvantum and the like) make it crash or warn,
              # and nothing from outside may end up in .venv
              unset QT_PLUGIN_PATH QML2_IMPORT_PATH QT_STYLE_OVERRIDE PYTHONPATH
              source ./scripts/dev.sh
            '';
        };
      }
    );
  };
}
