[build-system]
requires = [ "setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bem-fmm-python"
version = "0.1.0"
description = "Charge based boundary element fast multipole method"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "Shawn Pande", email = "spande@wpi.edu" },
  { name = "Simon Hao", email = "shao1@wpi.edu" },
  { name = "Guillermo Nunez Ponasso", email = "gcnunez@wpi.edu" },
  { name = "Drumm Derek", email = "dadrumm@wpi.edu" },
]
license = { text = "proprietary" }

dependencies = [
    "numpy==2.4.4",
    "vedo==2026.6.1",
    "scipy==1.17.1",
    "matplotlib",
    "joblib==1.5.3",
    "scikit-learn==1.9.0",
    "PySide6==6.11.1",
    "pyyaml==6.0.3",
    "typer==0.27.0",
    # These come from our index
    "fmm3dpyfast",
    "cbemfmm",
]

# [project.urls]
# Repository = "https://github.com//bem-fmm-python"

[project.optional-dependencies]
dev = [
  "pytest>=7.4.0", "jupyter>=1.0.0", "sphinx", "sphinx_mdinclude",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["bemfmm", "apps"]
# TODO find a better name for apps

[tool.setuptools.package-data]
apps = ["assets/**/*", "gui/*.ui", "tms/*.mat"]

[project.scripts]
tms_coil_navigator = "apps.gui.__main__:app"
bemfmm_tms = "apps.tms.__main__:app"
bemfmm_plot = "apps.plot.__main__:app"
bemfmm_sphere = "apps.sphere_3L.__main__:app"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"] # TODO have actual unit tests
python_functions = ["test_*"]
pythonpath = ["src"]

[tool.uv]
index-url = "https://pandecode.github.io/FMM3D/simple/"
extra-index-url = ["https://pypi.org/simple"]
